### PR TITLE
fix(docs): correct description of auto connect prop

### PR DESCRIPTION
**Pull request by YUN-RU-TSENG**
# Fixes Doc description error

**This PR fixes the incorrect description in the document.**

I use v1.20.0

The current document explains that the `Connector` of `auto-connect` receives the parameter param, which includes the source node id and target node id. The example describes that these values can be obtained using `param.source.id` and `param.target.id`, but in reality, undefined will be obtained. The correct way to write it should be `param.source` and `param.target` to obtain the id.

Here is the actual param object:
```json
{
    "source": "1",
    "sourceHandle": "1__handle-right",
    "target": "2",
    "targetHandle": "2__handle-left"
}
```

### Current erroneous document example:
```html
<script setup>
import { ref } from 'vue'

const elements = ref([/** elements omitted for simplicity */])

const connector = (params) => {
  if (params.source.id === params.target.id) {
    return false
  }

  return {
    id: `edge-${params.source.id}-${params.target.id}`, // undefined
    source: params.source.id, // undefined
    target: params.target.id, // undefined
    label: `Edge ${params.source.id}-${params.target.id}`, // undefined
    animated: true,
  }
}
</script>

<template>
  <VueFlow v-model="elements" :auto-connect="connector" />
</template>
```

### Modified version:

```html
<script setup>
import { ref } from 'vue'

const elements = ref([/** elements omitted for simplicity */])

const connector = (params) => {
  if (params.source === params.target) {
    return false
  }

  return {
    id: `edge-${params.source}-${params.target}`,
    source: params.source,
    target: params.target,
    label: `Edge ${params.source}-${params.target}`,
    animated: true,
  }
}
</script>

<template>
  <VueFlow v-model="elements" :auto-connect="connector" />
</template>
```

The above is what I discovered while using the library. If I have any misunderstandings, please feel free to point them out at any time.

### CODE REVIEW

**Comment by bcakmakoglu** [comment]
Thanks for the PR :) I'll take a look and merge it soon 👍

**Comment by bcakmakoglu** [comment]
You branched off from `develop` which you shouldn't have done as that is based on release 2.0.0 😅
Can you re-open this PR with a branch based on `master` instead?

That would be much appreciated ^^

**Comment by bcakmakoglu** [comment]
I'll be closing this as I resolved it in #977

**Comment by YUN-RU-TSENG** [comment]
sorry, recently work is too busy. thanks for resolved

**Pull request closed without merging**
