### PR TITLE
fix(controls): remove border, make the control look modern

### PR DESCRIPTION
**Pull request by nguyenvanduocit**
# 🚀 What's changed?

- remove the boder of controls

### CODE REVIEW

**Comment by bcakmakoglu** [comment]
Mh... why? Can you give me some image what this change would look like and argue why it's better? 😄

**Comment by nguyenvanduocit** [comment]
Current: 
image

New:
image

Style of current controls look "old", it's make me remember about Visual Basic, and does not consistant with other style of vue-flow, new design make it more modern.

**Comment by bcakmakoglu** [comment]
Mh... I see. Looks like React Flow has `border: none` as well so the change seems acceptable :)

**Review by bcakmakoglu — APPROVED** [review]

**Comment by bcakmakoglu** [comment]
Will be released soon (sometime this week) 👍

**Pull request merged**
