### PR TITLE
chore(docs): update node.md

### PR DESCRIPTION
**Pull request by Thanakorn-ki**
# 🚀 What's changed?

- The import name needs to be corrected. I'm just changing the name to the correct one.

# 🐛 Fixes

- [x] Rename from 'CustomNode` of import from `OverwriteCustomNode.vue` to `OverwriteCustomNode`.

### CODE REVIEW

**Comment by bcakmakoglu** [comment]
Thanks for the PR, I'll merge it asap :)

**Review by bcakmakoglu — APPROVED** [review]

**Comment by bcakmakoglu** [comment]
Can you do me a favor and edit the commit message to `chore(docs): update node.md`?

**Comment by Thanakorn-ki** [comment]
> Can you do me a favor and edit the commit message to `chore(docs): update node.md`?

Sure, I will send a commit message soon.

**Comment by Thanakorn-ki** [comment]
@bcakmakoglu I have already committed message to `chore(docs): update node.md`

**Pull request merged**
